(.venv) (base) mahdi@s-8d3a265e testing-python-exercise-wt2425 % pytest -s
========================================== test session starts ==========================================
platform darwin -- Python 3.12.4, pytest-7.4.4, pluggy-1.0.0
rootdir: /Users/mahdi/Documents/SSE Exercises/testing-python-exercise-wt2425
plugins: anyio-4.2.0
collected 5 items                                                                                       

tests/integration/test_diffusion2d.py ..
tests/unit/test_diffusion2d_functions.py Fdt = 0.0005000000000000001
..

=============================================== FAILURES ================================================
________________________________________ test_initialize_domain _________________________________________

    def test_initialize_domain():
        """
        Check function SolveDiffusion2D.initialize_domain
        """
        solver = SolveDiffusion2D()
    
        _w = 25.
        _h = 50.
        _dx = 0.5
        _dy = 0.7
    
        solver.initialize_domain(w=_w, h=_h, dx=_dx, dy=_dy)
    
>       assert solver.nx == 50
E       assert 100 == 50
E        +  where 100 = <diffusion2d.SolveDiffusion2D object at 0x118514f20>.nx

tests/unit/test_diffusion2d_functions.py:22: AssertionError
======================================== short test summary info ========================================
FAILED tests/unit/test_diffusion2d_functions.py::test_initialize_domain - assert 100 == 50
====================================== 1 failed, 4 passed in 0.32s ======================================
(.venv) (base) mahdi@s-8d3a265e testing-python-exercise-wt2425 % 